apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: rack-100-ippool
spec:
  cidr: 192.168.100.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "100"

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: rack-101-ippool
spec:
  cidr: 192.168.101.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "101"